site_name: 2020_5BI_Team6_Software_Doc
nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management plan': 'Software Project Management Plan.md'
    - 'Business Model Canvas': 'Business Model Canvas/index.md'
    - 'Project Model Canvas': 'Project Model Canvas.md'
    
theme:
    name: readthedocs

use_directory_urls: true
